### ISSUE TITLE
Some items italicized in JSX files with React language selected

### ISSUE THREAD

**Issue by chazzlabs** [ginfuru/vscode-onedark-raincoat#11]
The screenshot below has several instances of italicized items that I noticed when opening VS Code this morning, and after disabling/enabling my extensions it seems that onedark-raincoat is responsible for them.  Is there any way to disable this?  I was unable to find a way to do this after some searching in the VS Code settings.

![image](https://user-images.githubusercontent.com/3136972/46352944-fcf97b00-c628-11e8-8eb1-18a3d926d66e.png)

**Comment by edheltzel** [comment]
I use Dank Mono for programming -- Looks like I need to create a version of both themes to not have italics. 

I'll publish a new release here shortly.

**Comment by edheltzel** [comment]
@chazzlabs Release `v0.5.0` was just submitted to VSCode marketplace  -- I just removed the italics from the two new color scheme options... hopefully that helps. Let me know if you're still seeing anything and I'll just revert everything back.
