### ISSUE TITLE
Create New Icon

### ISSUE THREAD

**Issue by edheltzel** [ginfuru/vscode-onedark-raincoat#13]
One Dark Rain Coat  should have a better icon

child of #12

**Comment by nox-moon** [comment]
I tried to create a new logo/icon for you. I hope you like it.


![logo](https://user-images.githubusercontent.com/43906683/46916030-0da8da00-cfb5-11e8-9535-5a04ab550005.png)

**Comment by edheltzel** [comment]
@nox-moon  doesn't look bad at all
