### ISSUE TITLE
Not an issue. The font name

### ISSUE THREAD

**Issue by ivandj** [ginfuru/vscode-onedark-raincoat#17]
Sorry. This is not an issue. Just a question.
What is the font you are using in the 1st 2 screenshots:
https://raw.githubusercontent.com/ginfuru/vscode-onedark-raincoat/master/images/js.png

**Comment by ivandj** [comment]
Found it:
https://dank.sh/

**Comment by edheltzel** [comment]
@ivandj Hey sorry yeah - I use Dank Mono - totally worth the $
