### ISSUE TITLE
Lower contrast for primary highlight color

### ISSUE THREAD

**Issue by yeaen** [ginfuru/vscode-onedark-raincoat#22]
Could the primary highlight for the 1dark raincoat variants be less bright? It's hard to read red text on bright purple.

Specifically for me, when using the find tab, it's hard to read the selected result in the editor. So when searching for something like "editor", it's hard to see if it's "editor" or "Editor" in text.

https://i.imgur.com/yO7Sf8G.mp4

**Comment by edheltzel** [comment]
@y-a-n-w-a-n-g 
If you want to add the following to your vscode settings JSON
```json
"workbench.colorCustomizations":{
    "[1Dark RainCoat Bright]": {
      "editor.findMatchBackground": "#004971"
    },
}
```
You can change this to whatever color you like -- if you want to make a PR more than happy to accept it.
