### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by jsbUSMC** [ginfuru/vscode-onedark-raincoat#6]
I don't know if this is a serious issue for many, but I've found that the comments' contrast with the background makes them very hard to read and after awhile hurts my eyes. I love this theme, but my only suggestion is to edit the comment colors from the previous value of `#5C367085`, to remove the alpha channel for a new value `#5C3670`:

```json
...
"tokenColors" : [
  ...
  {
    "name": "Comments",
    "scope": "comment, punctuation.definition.comment",
      "settings": {
        "foreground": "#5C6370",
        "fontStyle": "italic"
      }
  },
  ...
],
...
```

It doesn't break the style of the theme, in my opinion, and makes it much more readable due to the increased contrast. Thank you.

**Comment by edheltzel** [comment]
@jsbUSMC I don't have any issues with that - though it looks like that you've got a purplish color for the comments - The color should be `#5C6370`  versus `#5C3670` _(assuming it’s a typo)_

```json
    {
      "name": "Comments",
      "scope": "comment, punctuation.definition.comment",
      "settings": {
        "foreground": "#5C637085",
        "fontStyle": "italic"
      }
    }
```
comments with color `#5C6370 `
![comments with color `#5C6370 `](http://port.d.pr/nbgoCR+)

comments with color `#5C637085`
![comments with color `#5C637085`](http://port.d.pr/143cie+)

**Comment by edheltzel** [comment]
@jsbUSMC looking at them side-by-side I'll have to agree with you.

**Comment by jsbUSMC** [comment]
Appreciate that you've caught the typo! Thank you for your feedback!
