### ISSUE TITLE
Seems like something broke with the latest update

### ISSUE THREAD

**Issue by joshjg** [ginfuru/vscode-onedark-raincoat#8]
Seems to be really red-green heavy, tokens are italicized unnecessarily, etc.

**Comment by edheltzel** [comment]
@joshjg Could you shoot me over a example of what you're seeing. I have a highly accurate color monitor and that might be the issue.

**Comment by joshjg** [comment]
<img width="663" alt="screen shot 2017-10-03 at 1 26 29 pm" src="https://user-images.githubusercontent.com/21149010/31139113-8d2fd1f6-a83e-11e7-9632-59a0678bb1dd.png">
Here's an example.

**Comment by edheltzel** [comment]
@joshjg You're right - I didn't open up any React or JS files... looks like i removed something I didn't mean too.

I'll have this fix shortly.

**Comment by edheltzel** [comment]
@joshjg check for updates and see if that worked for you.

**Comment by joshjg** [comment]
@ginfuru Looks great! Thanks.
